using System;
namespace jBot.Referee.Business
{
    public class Referee
    {
        string[] _refereeNames = new string[] {
            "Hoss Hardcore",
            "Alan Asslap",
            "Pete Pleasure",
            "Tommy Tosser",
            "Slappy Sexbomb",
            "Woody Longbone",
            "Steve Stiffbone",
            "Woody Wanker",
            "Billy Boner",
            "Harry Hardon",
            "Larry Lovebone",
            "Doggie Daddy",
            "Nick Naughty",
            "Luke Longbone",
            "Micky Meat",
            "Kevin Kinky",
            "Willy Vitale",
            "Jack Jizzpump",
            "Randy Rockstiff",
            "Lance Lovepump",
            "Jeremy Jizz",
            "Tony Tounge",
            "Jamie Jerkoff",
            "Ben Dover",
            "Lorenzo Lovegun",
            "Steve Stiffler",
            "Scott Sexpump",
            "Randy Rockhard",
            "Casey Cummings",
            "Benny Balls",
            "William Wood",
            "Paulie Pecker",
            "Carl Cumsalot",
            "Jerry Jerksalot",
            "Hank Horny",
            "Jimmy Jammer",
            "Nolan Nastee",
            "Nikki Nuttz",
            "Will Wankalot",
            "Danny Doggy",
            "Harry Hotbone",
            "Henri Hornee",
            "Sly Steeldong",
            "Barry Blowme",
            "Nicky Lovecolt",
            "Randy Rockhard",
            "Joey Rambone",
            "Ricky Lovenuts",
            "Terry Titfuck",
            "Mike Meatmaster",
            "Daddy Lovebone",
            "Jimmy Jizzball",
            "Seargent Sexy",
            "Major Meatbone",
            "Private Pecker",
            "Buck Naked",
            "Jake Jizzpump",
            "Ramone Lovegod",
            "Antonio Assman",
            "Harry Humper",
            "Clint Meatwood",
            "Tom Spanks",
            "Master Bater",
            "Bruce Ballslap",
            "David Ducockny",
            "Denzel Wankington",
            "Nikki Lovegod",
            "Seargent Love",
            "Kurt Kinky",
            "Tony Longbone",
            "Henry Hardcore",
            "Stevie Stiff",
            "Franky Fuckbone",
            "Billy Steeldong",
            "Doctor Hardlove",
            "Ronnie Rammer",
            "Lee Lovetounge",
            "Clive Cockster",
            "Sly Slapalot",
            "Woody Humpalot",
            "Benny Backdoor",
            "Willy Jizznuts",
            "Major Steelbone",
            "Homer Hardon",
            "Billy Buttlove",
            "Lee Longstroke",
            "Micky Hotlove",
            "Jake Jammer",
            "Scott Loveshot",
            "Kelly Kumshot",
            "Antonio Assram"
        };

        public string GetName(string originalName)
        {
            var namePos = originalName.ToNumber(_refereeNames.Length - 1);
            return _refereeNames[namePos];
        }
    }
}
